file_cache_path           "/tmp/chef"
data_bag_path             "/root/chef/data_bags"
encrypted_data_bag_secret "/root/chef/data_bag_key"
cookbook_path             "/root/chef/site-cookbooks"
role_path                 "/root/chef/roles"
